spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/dobaerangdb
    username: myadmin
    password: dlwjdals1*

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8070

